/*Codded by Thevindu Hansara
*/

const Asena = require('../events');
const {MessageType} = require('@adiwajshing/baileys');

Asena.addCommand({pattern: 'zpack', fromMe: false}, (async (message, match) => {

    await message.sendMessage("▬▬▬ *💕 Kyouko 💕* ▬▬▬\n\n```ZPACK COMMANDS ;```\n\n*🎯 Command:* ```.z3d```\n\n*🎯 Command:* ```.z8bit```\n\n*🎯 Command:* ```.zal```\n\n*🎯 Command:* ```.zaveng```\n\n*🎯 Command:* ```.zbneon```\n\n*🎯 Command:* ```.zbokeh```\n\n*🎯 Command:* ```.zbook```\n\n*🎯 Command:* ```.zbp```\n\n*🎯 Command:* ```.zbrand```\n\n*🎯 Command:* ```.zbreake```\n\n*🎯 Command:* ```.zcc2```\n\n*🎯 Command:* ```.zcl```\n\n*🎯 Command:* ```.zcoding```\n\n*🎯 Command:* ```.zcrismes```\n\n*🎯 Command:* ```.zd2a```\n\n*🎯 Command:* ```.zdneon```\n\n*🎯 Command:* ```.zdropwater```\n\n*🎯 Command:* ```.zemoj```\n\n*🎯 Command:* ```.zepep```\n\n*🎯 Command:* ```.zff```\n\n*🎯 Command:* ```.zfire```\n\n*🎯 Command:* ```.zflame```\n\n*🎯 Command:* ```.zflower```\n\n*🎯 Command:* ```.zgalaxy```\n\n*🎯 Command:* ```.zgb```\n\n*🎯 Command:* ```.zglow```\n\n*🎯 Command:* ```.zgplay```\n\n*🎯 Command:* ```.zgtext```\n\n*🎯 Command:* ```.zharry```\n\n*🎯 Command:* ```.zhorror```\n\n*🎯 Command:* ```.zht```\n\n*🎯 Command:* ```.zleave```\n\n*🎯 Command:* ```.zlight```\n\n*🎯 Command:* ```.zlion```\n\n*🎯 Command:* ```..zlogo```\n\n*🎯 Command:* ```..zlol```\n\n*🎯 Command:* ```.zlr```\n\n*🎯 Command:* ```.zlt```\n\n*🎯 Command:* ```.zluxury```\n\n*🎯 Command:* ```.zmarval```\n\n*🎯 Command:* ```.zmm```\n\n*🎯 Command:* ```.znaruto```\n\n*🎯 Command:* ```.zneonx```\n\n*🎯 Command:* ```.zon3d```\n\n*🎯 Command:* ```.zpaper```\n\n*🎯 Command:* ```.zpark```\n\n*🎯 Command:* ```.zphlogo```\n\n*🎯 Command:* ```.zpubg```\n\n*🎯 Command:* ```.zrandom```\n\n*🎯 Command:* ```.zsandw```\n\n*🎯 Command:* ```.zsilk```\n\n*🎯 Command:* ```.zsky```\n\n*🎯 Command:* ```.zsmoke```\n\n*🎯 Command:* ```.zsn```\n\n*🎯 Command:* ```.zspace```\n\n*🎯 Command:* ```.zsplay```\n\n*🎯 Command:* ```.zst```\n\n*🎯 Command:* ```.ztlogo```\n\n*🎯 Command:* ```.ztoxic```\n\n*🎯 Command:* ```.zuwo```\n\n*🎯 Command:* ```.zwc```\n\n*🎯 Command:* ```.zwolf```\n");
}));
